#Crear la base de datos
CREATE DATABASE BIBLIOTECA;

#Usar la base de datos
USE BIBLIOTECA;

#Crear tablas
CREATE TABLE AUTOR(
    ID_AUTOR INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
    );
    
CREATE TABLE LIBRO(
    ID_LIBRO INT NOT NULL PRIMARY KEY,
    TITULO VARCHAR(50) NOT NULL,
    ISBN VARCHAR(25) NOT NULL,
    EDITORIAL VARCHAR(25) NOT NULL,
    PAGINAS INT NOT NULL
    );
    
    
CREATE TABLE USUARIO(
    ID_USUARIO INT NOT NULL PRIMARY KEY,
    DOCUMENTO INT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    DIRECCION VARCHAR (50) NOT NULL,
    CORREO VARCHAR(50) NOT NULL,
    TELEFONO INT NOT NULL
    );
    
    
    CREATE TABLE AUTOR_LIBRO(
        ID_AUTOR_LIBRO INT NOT NULL PRIMARY KEY,
        ID_AUTOR INT NOT NULL,
        ID_LIBRO INT NOT NULL
        
    );
    
    
    CREATE TABLE EJEMPLAR(
    ID_EJEMPLAR INT NOT NULL PRIMARY KEY,
        LOCALIZACION VARCHAR(50) NOT NULL,
        ID_LIBRO INT NOT NULL
    );
    
    CREATE TABLE PRESTAMO(
     ID_PRESTAMO INT NOT NULL PRIMARY KEY,
    FECHA_PRESTAMO DATE NOT NULL,
    FECHA_DEVOLUCION DATE NOT NULL,
    ID_EJEMPLAR INT NOT NULL,
    ID_USUARIO INT NOT NULL);
    
    #CREAR FORANEAS
    
    ALTER TABLE AUTOR_LIBRO ADD CONSTRAINT FK_AUTOR_LIBRO_AUTOR FOREIGN KEY(ID_AUTOR) 
    REFERENCES AUTOR(ID_AUTOR);
    
    ALTER TABLE AUTOR_LIBRO ADD CONSTRAINT
    FK_AUTOR_LIBRO_LIBRO FOREIGN KEY(ID_LIBRO)
    REFERENCES LIBRO(ID_LIBRO);
    
    ALTER TABLE EJEMPLAR ADD CONSTRAINT
    FK_EJEMPLAR_LIBRO FOREIGN KEY(ID_LIBRO)
    REFERENCES LIBRO(ID_LIBRO);
    
    ALTER TABLE PRESTAMO ADD CONSTRAINT
    FK_PRESTAMO_EJEMPLAR FOREIGN KEY(ID_EJEMPLAR)
    REFERENCES EJEMPLAR(ID_EJEMPLAR);
    
    ALTER TABLE PRESTAMO ADD CONSTRAINT
    FK_PRESTAMO_USUARIO FOREIGN KEY(ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO);
    